INSERT INTO users (name, email) VALUES ('Alice', 'alice@example.com');
INSERT INTO users (name, email) VALUES ('Bob', 'bob@example.com');
INSERT INTO users (name, email) VALUES ('Charlie', 'charlie@example.com');
INSERT INTO users (name, email) VALUES ('David', 'david@example.com');
INSERT INTO users (name, email) VALUES ('Eve', 'eve@example.com');
INSERT INTO users (name, email) VALUES ('Frank', 'frank@example.com');
INSERT INTO users (name, email) VALUES ('Grace', 'grace@example.com');
INSERT INTO users (name, email) VALUES ('Heidi', 'heidi@example.com');
INSERT INTO users (name, email) VALUES ('Ivan', 'ivan@example.com');
INSERT INTO users (name, email) VALUES ('Judy', 'judy@example.com');
INSERT INTO users (name, email) VALUES ('Karl', 'karl@example.com');
INSERT INTO users (name, email) VALUES ('Linda', 'linda@example.com');
INSERT INTO users (name, email) VALUES ('Mike', 'mike@example.com');
INSERT INTO users (name, email) VALUES ('Nancy', 'nancy@example.com');
INSERT INTO users (name, email) VALUES ('Oscar', 'oscar@example.com');
INSERT INTO users (name, email) VALUES ('Patty', 'patty@example.com');
INSERT INTO users (name, email) VALUES ('Quinn', 'quinn@example.com');
INSERT INTO users (name, email) VALUES ('Rachel', 'rachel@example.com');
INSERT INTO users (name, email) VALUES ('Steve', 'steve@example.com');
INSERT INTO users (name, email) VALUES ('Tina', 'tina@example.com');
INSERT INTO users (name, email) VALUES ('Uma', 'uma@example.com');
INSERT INTO users (name, email) VALUES ('Victor', 'victor@example.com');
INSERT INTO users (name, email) VALUES ('Wendy', 'wendy@example.com');
INSERT INTO users (name, email) VALUES ('Xavier', 'xavier@example.com');
INSERT INTO users (name, email) VALUES ('Yara', 'yara@example.com');
INSERT INTO users (name, email) VALUES ('Zoe', 'zoe@example.com');
INSERT INTO users (name, email) VALUES ('Liam', 'liam@example.com');
INSERT INTO users (name, email) VALUES ('Olivia', 'olivia@example.com');
INSERT INTO users (name, email) VALUES ('Noah', 'noah@example.com');
INSERT INTO users (name, email) VALUES ('Emma', 'emma@example.com');
INSERT INTO users (name, email) VALUES ('Lucas', 'lucas@example.com');
INSERT INTO users (name, email) VALUES ('Ava', 'ava@example.com');

INSERT INTO products (name, price) VALUES ('Laptop', 1200.00);
INSERT INTO products (name, price) VALUES ('Mouse', 25.00);
INSERT INTO products (name, price) VALUES ('Keyboard', 75.00);
INSERT INTO products (name, price) VALUES ('Monitor', 300.00);
INSERT INTO products (name, price) VALUES ('Webcam', 50.00);
INSERT INTO products (name, price) VALUES ('Headphones', 150.00);
INSERT INTO products (name, price) VALUES ('Microphone', 80.00);
INSERT INTO products (name, price) VALUES ('Printer', 200.00);
INSERT INTO products (name, price) VALUES ('External Hard Drive', 100.00);
INSERT INTO products (name, price) VALUES ('USB Flash Drive', 15.00);
INSERT INTO products (name, price) VALUES ('Router', 60.00);
INSERT INTO products (name, price) VALUES ('Smartwatch', 250.00);
INSERT INTO products (name, price) VALUES ('Smartphone', 800.00);
INSERT INTO products (name, price) VALUES ('Tablet', 400.00);
INSERT INTO products (name, price) VALUES ('E-Reader', 120.00);
INSERT INTO products (name, price) VALUES ('Gaming Console', 500.00);
INSERT INTO products (name, price) VALUES ('VR Headset', 400.00);
INSERT INTO products (name, price) VALUES ('Drone', 300.00);
INSERT INTO products (name, price) VALUES ('Action Camera', 200.00);
INSERT INTO products (name, price) VALUES ('Bluetooth Speaker', 70.00);
INSERT INTO products (name, price) VALUES ('Projector', 350.00);
INSERT INTO products (name, price) VALUES ('Smart Light Bulb', 20.00);
INSERT INTO products (name, price) VALUES ('Smart Plug', 15.00);
INSERT INTO products (name, price) VALUES ('Robot Vacuum', 250.00);
INSERT INTO products (name, price) VALUES ('Coffee Maker', 80.00);
INSERT INTO products (name, price) VALUES ('Blender', 60.00);
INSERT INTO products (name, price) VALUES ('Toaster', 40.00);
INSERT INTO products (name, price) VALUES ('Air Fryer', 100.00);
INSERT INTO products (name, price) VALUES ('Electric Kettle', 30.00);
INSERT INTO products (name, price) VALUES ('Slow Cooker', 50.00);
INSERT INTO products (name, price) VALUES ('Microwave', 120.00);
INSERT INTO products (name, price) VALUES ('Dishwasher', 600.00);